# Generated by Django 3.1.6 on 2021-04-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work', models.CharField(choices=[('S', 'String Replacement'), ('C', 'Cleaning'), ('P', 'Part Replacement'), ('F', 'Fret Level & Polish'), ('A', 'Full Setup')], default='S', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
