# Generated by Django 3.1.6 on 2021-04-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='maintenance date'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='straps',
            field=models.ManyToManyField(to='main_app.Strap'),
        ),
    ]
